Add files via upload
etozhestep/lesson_1 pull request #1
Opened 2021-01-30 16:36 UTC by etozhestep

2021-02-01 21:44 UTC, AntonShtabnoy requested changes

2021-02-01 21:44 UTC, AntonShtabnoy commented on src/by/stepaniuk/lesson1/task4.java
> +public class task4 {
Название классов нужно писать с большой буквы Task4

2021-02-01 21:44 UTC, AntonShtabnoy commented on src/by/stepaniuk/lesson1/task4.java
> +        int b=(n%100)/10;
Обрати внимание на форматирование a = n % 10 - везде должны быть пробелы между символами. Автоформатирование делается сочетанием клавиш ctrl+alt+L

2021-02-01 21:44 UTC, AntonShtabnoy commented on src/by/stepaniuk/lesson1/task4.java
> +        int b=(n%100)/10;
Называть лучше не a, b, c - а хотябы firstDigit и тд

2021-02-01 21:44 UTC, AntonShtabnoy commented on src/by/stepaniuk/lesson1/task5.java
> +        if ((a!=b)&&(a!=c)&&(a!=d)&&(b!=c)&&(b!=d)&&(c!=d)) {
Подумай как можно уменьшить кол-во условий до 3

2021-02-01 21:46 UTC, AntonShtabnoy requested changes

2021-02-01 21:46 UTC, AntonShtabnoy commented on src/by/stepaniuk/lesson1/task1.txt
> +0x1C=16^1*1+16^0*12=28
Про задание 2: Команда в консоли должна выглядеть java -cp /home Main Privet
И вот эту строку(Privet) что я передаю в конце должна вывести программа на экран.

2021-02-01 21:54 UTC, AntonShtabnoy requested changes

2021-02-01 21:54 UTC, AntonShtabnoy commented on src/by/stepaniuk/lesson1/task7.java
> +        System.out.print("Радиус круга: ");
А стороны могут быть дробными?

2021-02-02 12:04 UTC, etozhestep commented on src/by/stepaniuk/lesson1/task7.java
> +        System.out.print("Радиус круга: ");
так ведь int хранит целое число или я что-то не так понимаю?

2021-02-07 22:19 UTC, AntonShtabnoy requested changes

2021-02-07 22:19 UTC, AntonShtabnoy commented on src/by/stepaniuk/lesson3/Task3.java
> +        for (int i = 1; i <= 256; i++) {
Неверная сумма будет не хватать единицы

2021-02-07 22:19 UTC, AntonShtabnoy commented on src/by/stepaniuk/lesson3/Task4.java
> +        for (int d = 1; d<=b; d++){
Форматирование d <= b - везде пробелы ставь

2021-02-07 22:19 UTC, AntonShtabnoy commented on src/by/stepaniuk/lesson3/Task5.java
> +            ameb = ameb + 2;
Старайся переводить на английский слова - а не писать латинецей - иностранцы не поймут код

2021-02-07 22:19 UTC, AntonShtabnoy commented on src/by/stepaniuk/lesson3/Task5.java
> +            ameb = ameb + 2;
Неверное решение. Смотри размножение будет происходить след образом 
![image](https://user-images.githubusercontent.com/26979319/107160967-8f08af80-69aa-11eb-9bcc-475d0865e929.png)
т.е каждый раз новая амеба будет также делится

2021-02-07 22:19 UTC, AntonShtabnoy commented on src/by/stepaniuk/lesson3/Task6.java
> +        for (int i = 2; i <= dney; i++) {
Почему с двойки цикл?

2021-02-07 22:19 UTC, AntonShtabnoy commented on src/by/stepaniuk/lesson3/Task6.java
> +        System.out.println(sum + 1000);
Что за прибавление в строке вывода?

2021-02-07 22:19 UTC, AntonShtabnoy commented on src/by/stepaniuk/lesson3/Task7.java
> +            if (array[i] >= 5) {
Почему сравнение с 5?

2021-02-07 22:19 UTC, AntonShtabnoy commented on src/by/stepaniuk/lesson3/Task7.java
> +        }
Почему сравнение с 0?

2021-02-07 22:19 UTC, AntonShtabnoy commented on src/by/stepaniuk/lesson3/Task7.java
> +        int index2 = 0;
по названием индексов ничего не понятно что в них хранится

2021-02-07 22:19 UTC, AntonShtabnoy commented on src/by/stepaniuk/lesson3/Task7.java
> +        for (int i = index1 + 1; i < index2; i++)
В цикле for тело лучше писать в {}

2021-02-07 22:19 UTC, AntonShtabnoy commented on src/by/stepaniuk/lesson3/Task8.java
> +        }
Лучше в цикле ввести переменную i - в твоем случае ты потерял входные данные, и ели нужно будет что-то еще с ними сделать, все сломается

2021-02-07 22:33 UTC, AntonShtabnoy requested changes

2021-02-07 22:33 UTC, AntonShtabnoy commented on src/by/stepaniuk/lesson3/Task3.java
> +        for (int i = 1; i <= 256; i++) {
И там не просто четные числа в сумме, там есть определенная закономерность, и не все четные числа туда попадают

2021-02-10 18:57 UTC, etozhestep commented on src/by/stepaniuk/lesson2/Task4.java
> +            System.out.print(n);
изменил

2021-02-10 19:38 UTC, etozhestep commented on src/by/stepaniuk/lesson2/Task5.java
> +            System.out.println("все числа различны");
вроде как подправил, но не уверен что именно это требовалось. решение все равно грамоздкое.

2021-02-14 19:49 UTC, AntonShtabnoy reviewed
Не вижу на половину моих комментарием - просто закрыты комментарии и ничего не исправлено.

2021-02-14 19:49 UTC, AntonShtabnoy commented on src/by/stepaniuk/lesson2/Task5.java
> +            if ((n == r) || (n == k) || (n == j) || (r == k)) {
Цикл - это повторяющееся действие, а та и сам на копировал еще своих повторений - и что в итоге вышло? На уроке обсуждали, что цифры занести в массив, а потом через массив проверить есть ли повторения.

2021-02-14 20:22 UTC, etozhestep commented
> Не вижу на половину моих комментарием - просто закрыты комментарии и ничего не исправлено.

исправлено же. Lesson 2 task 4: неправильно выводил конечное число. исправил и вывожу уже умножая на степень. Lesson 3 task 2: неправильно сортировал. исправил с помощью сортировки пузырьком. Lesson 3 task 3: выводил сумму четых чисел до 256. исправил и выводит правильно. Lesson 3 task 4: добавил нужые пробелы в оформелии и больше не было проблем. Lesson 3 task5: неправильно считал кол-во амеб. исправил.Lesson 3 task 6: неправильно называл переменые. исправил на англ языке. Lesson 3 task 8: не все переменные в цикле были. исправил применив другой тип цикла. Просто исправил эти ошибки и решил resolve conversation нажать.

2021-02-14 20:30 UTC, AntonShtabnoy commented
Task 7 я не просто задал вопросы насчет 5, 0.  6 задание частично исправлено 8 мин назад, но про 1000 в sout так и не испаврлено. Это то что я сразу вижу

2021-02-14 20:36 UTC, etozhestep commented
> Task 7 я не просто задал вопросы насчет 5, 0.  6 задание частично исправлено 8 мин назад, но про 1000 в sout так и не испаврлено. Это то что я сразу вижу

Таск 7 и задания с Lesson 5 у меня на рабочем компе остались. Только завтра смогу запушить. А про таск 6 забыл исправить 1000 в sout, сейчас исправлю.

2021-02-14 20:39 UTC, AntonShtabnoy commented
Ну вы должны понимать - я же не могу постоянно следить за вашими обновлениями, я один раз прошелся - посмотрел исправления - всех нет - то и написал. Вас же 15  - не так легко за всеми следить - и смотреть что где по одному исправляет - все смотрю вместе.

2021-02-14 21:08 UTC, etozhestep commented
> Ну вы должны понимать - я же не могу постоянно следить за вашими обновлениями, я один раз прошелся - посмотрел исправления - всех нет - то и написал. Вас же 15  - не так легко за всеми следить - и смотреть что где по одному исправляет - все смотрю вместе.

Да, понимаю. Прошу прощения, затупил. Буду исправляться!

2021-02-22 19:07 UTC, AntonShtabnoy commented on src/by/stepaniuk/lesson5/Task2/Customer.java
> +    }
Нам нужно написать метод который можно использовать во всех местах, т.е нам нужно написать один метод печатания массива, чтобы ты ему на вход давал любой массив покупателей, а он тебе его выводил содержимое. Твой метод забит под какой-то один случай

2021-02-22 19:07 UTC, AntonShtabnoy commented on src/by/stepaniuk/lesson5/Task2/Customer.java
> +                }
Пересмотри реализацию алгоритма пузырька - там изменений позиций элементов делается в одном месте

2021-02-22 19:07 UTC, AntonShtabnoy commented on src/by/stepaniuk/lesson5/Task3/Books.java
> +public class Books {
название класса должно быть в единственном числе

2021-02-22 19:07 UTC, AntonShtabnoy commented on src/by/stepaniuk/lesson5/Task3/BooksActions.java
> +    public static Books[] booksAuthor(Books[] arr) {
методы поиска принято называть find - поиск одного элемента, findAll - поиск нескольких, findByAuthor (поиск одного элемента по автору)

2021-02-22 19:07 UTC, AntonShtabnoy commented on src/by/stepaniuk/lesson5/Task3/BooksActions.java
> +        }
аналогично continue тут лишний

2021-02-22 19:07 UTC, AntonShtabnoy commented on src/by/stepaniuk/lesson5/Task3/BooksActions.java
> +    }
читай коммент в другом задании про метод print

2021-02-22 19:07 UTC, AntonShtabnoy commented on src/by/stepaniuk/lesson6/Demo.java
> +    public void arrLenght (int length) {
Это должен быть конструктор

2021-02-22 19:07 UTC, AntonShtabnoy commented on src/by/stepaniuk/lesson6/Demo.java
> +    Integer[] arr;
подумать про модификаторы доступа

2021-02-22 19:07 UTC, AntonShtabnoy commented on src/by/stepaniuk/lesson6/Demo.java
> +public class Demo implements MySuperArray {
Demo - это класс для демонстарции функционала - ты тут его только реализовываешь, поэтому такое название сюда не подходит

2021-02-23 09:14 UTC, etozhestep commented on src/by/stepaniuk/lesson3/Task6.java
> +        double MetersOnFirstDay = 1000;
исправил

2021-02-23 09:14 UTC, etozhestep commented on src/by/stepaniuk/lesson3/Task6.java
> +        System.out.println(sum + MetersOnFirstDay);
исправил

2021-02-25 09:58 UTC, etozhestep commented on src/by/stepaniuk/lesson5/Task1/TimeInterval.java
> +    public int timeIntervalId;
ну у каждого интервала свой ид и так удобнее их выводить

2021-02-25 09:59 UTC, etozhestep commented on src/by/stepaniuk/lesson5/Task1/TimeInterval.java
> +    public TimeInterval(int seconds) {
исправил

2021-02-25 09:59 UTC, etozhestep commented on src/by/stepaniuk/lesson5/Task1/TimeInterval.java
> +    public static void outIntervalData(TimeInterval a) {
исправил

2021-02-25 09:59 UTC, etozhestep commented on src/by/stepaniuk/lesson5/Task1/TimeInterval.java
> +    }
исправил

2021-02-25 09:59 UTC, etozhestep commented on src/by/stepaniuk/lesson5/Task1/TimeInterval.java
> +            System.out.println("Период равны");
исправил

2021-02-25 11:33 UTC, etozhestep commented on src/by/stepaniuk/lesson5/Task1/Demo.java
> +package by.stepaniuk.lesson5.Task1;
исправил

2021-02-25 11:37 UTC, etozhestep commented on src/by/stepaniuk/lesson5/Task2/Customer.java
> +    public int bankNumber;
исправил

2021-02-25 11:37 UTC, etozhestep commented on src/by/stepaniuk/lesson5/Task2/Customer.java
> +    }
исправил

2021-02-25 12:23 UTC, etozhestep commented on src/by/stepaniuk/lesson5/Task2/Customer.java
> +    }
исправил

2021-02-25 12:24 UTC, etozhestep commented on src/by/stepaniuk/lesson5/Task2/Customer.java
> +    }
исправил

2021-02-25 12:24 UTC, etozhestep commented on src/by/stepaniuk/lesson5/Task2/Customer.java
> +                }
исправил

2021-02-26 08:29 UTC, etozhestep commented on src/by/stepaniuk/lesson5/Task2/Customer.java
> +            }
исправил

2021-02-26 08:30 UTC, etozhestep commented on src/by/stepaniuk/lesson5/Task3/Books.java
> +public class Books {
исправил

2021-02-26 08:49 UTC, etozhestep commented on src/by/stepaniuk/lesson5/Task3/BooksActions.java
> +    }
исправил

2021-02-26 08:49 UTC, etozhestep commented on src/by/stepaniuk/lesson5/Task3/BooksActions.java
> +        }
исправил

2021-02-26 08:51 UTC, etozhestep commented on src/by/stepaniuk/lesson5/Task3/BooksActions.java
> +    public static Books[] booksAuthor(Books[] arr) {
исправил

2021-02-28 21:34 UTC, merged